import type { Metadata } from 'next'
import {Lato} from 'next/font/google'
import './globals.css'
import {NextFont} from "next/dist/compiled/@next/font";

const lato: NextFont = Lato({ weight: ['400', '700', '900'], subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'SeoApp',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
